# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    # In the future, this should be switched to some persistent external storage
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    # Using this official mirror over https://github.com/psf/black lets us use
    # mypyc-compiled `black`, which is about 2x faster; see:
    # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
