DB_PATH = "test.db"
DB_VERSION = "1.0.0"
DB_HASH_ALGORITHM = "sha1"
DB_DEFAULT_DIGITS_COUNT = 6
DB_DEFAULT_TIME_STEP_SECONDS = 30

KEYRING_SERVICE_NAME = "onetimepass"
KEYRING_USERNAME = "master key"
