name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3.3
      with:
        python-version: "3.10"
        architecture: x64
        version: 2.7.4  # The version of PDM
        prerelease: false  # Disallow prerelease versions of PDM
        enable-pep582: true
        allow-python-prereleases: false
        cache: true
    - name: Install dependencies
      run: |
        pdm sync
    - name: Run unit tests
      run: |
        pdm run python -m unittest
